### ISSUE TITLE
With learner.to_fp16() I get error "RuntimeError: expected dtype Float but got dtype Half"

### ISSUE THREAD

**Issue by Lissanro** [nestordemeure/ManifoldMixupV2#1]
FP16 is important for better performance and preserving VRAM, some larger models cannot be trained at all without it on my videocard. Built-in MixUp() works without issues with to_fp16(). I get the following error with ManifoldMixup() (full error log: https://pastebin.com/HPMLwg6F):

```
~/Jupyter/manifold_mixup.py in hook_mixup(self, module, input, output)
    140         if not self.mixup_has_been_applied: # performs mixup
    141             output_dims = len(output.size())
--> 142             output = torch.lerp(output[self.shuffle], output, weight=unsqueeze(self.lam, n=output_dims-1))
    143             self.mixup_has_been_applied = True
    144             return output

RuntimeError: expected dtype Float but got dtype Half
```

**Comment by nestordemeure** [comment]
Did you try to run `torch.lerp` in isolation with all of its inputs set to half precision ?

My suspicion is that it could work in half but fails because the `weight` parameter is not converted to the proper precision (which is fixable).

If it still fails then `lerp` is indeed not compatible with half and it could be replaced by either a test (which would be very case specific) or an explicit call to the corresponding arithmetic operators.
